export const ADD_INGREDIENT = 'ADD'
export const REMOVE_INGREDIENT = 'REMOVE'
export const SET_INGREDIENTS = 'SET'
export const SET_INGREDIENTS_FAILED = 'SET_FAILED'

export const PURCHASE_BURGER_SUCCESS = 'PURCHASE_BURGER_SUCCESS'
export const PURCHASE_BURGER_FAILED = 'PURCHASE_BURGER_FAILED'
export const PURCHASING_BURGER = 'PURCHASING_BURGER'
export const PURCHASE_INIT = 'PURCHASE_INIT'

export const FETCH_ORDERS_INIT = 'FETCH_ORDERS_INIT'
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS'
export const FETCH_ORDERS_FAILED = 'FETCH_ORDERS_FAILED'

export const AUTH_INIT = 'AUTH_INIT'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_FAILED = 'AUTH_FAILED'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'
export const AUTH_SET_URL = 'AUTH_SET_URL'
